baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = '''Hi! I'm Denis'''
theme = 'ananke'

[languages]

  [languages.en]
    languageName = "ğŸ‡¬ğŸ‡§ English"
    weight = 1
    contentDir = "content/en"

  # English menu
  [[languages.en.menu.main]]
    name = "ğŸ’¼ Work"
    url = "/work/"
    weight = 2

  [[languages.en.menu.main]]
    name = "ğŸƒâ€â™‚ï¸ Sport"
    url = "/sport/"
    weight = 3
  
  [[languages.en.menu.main]]
    name = "ğŸŒ Travel"
    url = "/travel/"
    weight = 4
  
  [[languages.en.menu.main]]
    name = "ğŸŒ Posts"
    url = "/posts/"
    weight = 4

  [[languages.en.menu.main]]
    name = "ğŸ“„ CV"
    url = "/cv/"
    weight = 5

  [languages.ru]
    languageName = "ğŸ‡·ğŸ‡º Ğ ÑƒÑÑĞºĞ¸Ğ¹"
    weight = 1
    contentDir = "content/ru"

  # Russian menu
  [[languages.ru.menu.main]]
    name = "ğŸ’¼ Ğ Ğ°Ğ±Ğ¾Ñ‚Ğ°"
    url = "/work/"
    weight = 2
  
  [[languages.ru.menu.main]]
    name = "ğŸƒâ€â™‚ï¸ Ğ¡Ğ¿Ğ¾Ñ€Ñ‚"
    url = "/sport/"
    weight = 3
  
  [[languages.ru.menu.main]]
    name = "ğŸŒ ĞŸÑƒÑ‚ĞµÑˆĞµÑÑ‚Ğ²Ğ¸Ñ"
    url = "/travel/"
    weight = 4
  
  [[languages.ru.menu.main]]
    name = "ğŸ“„ Ğ ĞµĞ·ÑĞ¼Ğµ"
    url = "/cv/"
    weight = 5
